### Configuration for fakefriends.me
#
# in YAML format
#
slogan: 'No information &mdash; on everyone'
vousaussi: "You&#8217re a fake friend too!"
votrenom: "Your Name"
chercher: Search
permalien: "Permalink for @nom@&#8217s page:"
permaliencourt: "Permalink for this page:"
newmembers: "They just joined:"
monanniv: "It&#8217s my birthday today!"
bonanniv: "Happy Birthday to:"
jai_age_an: "I&#8217m @age@ years old."
neele: "Born @date@"
nele: "Born @date@"
mapensee: "My thoughts:"
moninfo: "My info:"
lesnamisdex: "@name@&#8217s @num@ friends:"
annees: years
formatheure: H:i
jhabite: "I live in"
phobia: "My fear:"
pied: |
  fakefriends.me is the first fake social network on the internet<br />none of the data is personal<br /><a href="http://spreadsheets.google.com/viewform?formkey=dFZELW1xSHdJc09hOWFRU1ZETTA4Mmc6MA.." target="_blank">participate<\/a> &#8226 <a href="http://per.sonn.es/@nom@">en fran&#231ais<\/a>
parauteur: by

# Sites for "my info"
sites:
  - http://rezo.net/backend/anglais
  - http://blog.foodista.com/feed/
  - http://feeds2.feedburner.com/fmylife

# Home page
home:
  titre: fakefriends.me
  title: "Welcome to fakefriends.me"
  statut: |
    <ul><li><a href="http://zzz.rezo.net/Herisson-moteur-de-per-sonn-es.html">Fakefriends.me goes GNU/AGPL.</a> Yay!</li></ul>
  info: |
    <div id="letter">
    <h2>A new social network concept</h2>
    <p>Hi,</p>
    <p>Fantastic success, given that we&#8217;ve not officially launched yet
    <br />
    already @inscrits@ members!</p>
    <p>it&#8217;s still time to join the <code>fakefriends.me</code> network</p>
    <p>or is it that you&#8217;re already a member?</p>
    <p><code>fakefriends.me</code> is a new social networking concept</p>
    <p style="text-align:right;">see you soon</p>
    </div>
    <object width="478" height="348"><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="http://vimeo.com/moogaloop.swf?clip_id=3999233&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=&amp;fullscreen=1" /><embed src="http://vimeo.com/moogaloop.swf?clip_id=3999233&amp;server=vimeo.com&amp;show_title=0&amp;show_byline=0&amp;show_portrait=0&amp;color=&amp;fullscreen=1" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="478" height="348"></embed></object>
    <p style="text-align:center;"><a href="http://vimeo.com/3999233">Everything is obvious with this film</a> by <a href="http://vimeo.com/user1462805">gud woman</a>.</p>

